name: Feature request triage bot

on:
  schedule:
    # Run at 15:00 every day
    - cron: '0 15 * * *'

jobs:
  feature_triage:
    if: github.repository == 'angular/components'
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/feature-request@c9d0bf5e5facaf816f0af90547728fb8752ef97e
        with:
          angular-robot-key: ${{ secrets.ANGULAR_ROBOT_PRIVATE_KEY }}
