name: Lock Inactive Issues

on:
  schedule:
    # Run at 00:00 every day
    - cron: '0 0 * * *'

permissions: read-all

jobs:
  lock_closed:
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/lock-closed@3bc93449e11b733260d0294305bf57240d7e0a81
        with:
          lock-bot-key: ${{ secrets.LOCK_BOT_PRIVATE_KEY }}
