name: Lock Inactive Issues

on:
  schedule:
    # Run at 00:00 every day
    - cron: '0 0 * * *'

jobs:
  lock_closed:
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/lock-closed@613f706bc2467da4064f51be09ba0f8f1c3cb57e
        with:
          lock-bot-key: ${{ secrets.LOCK_BOT_PRIVATE_KEY }}
