name: Lock Inactive Issues

on:
  schedule:
    # Run at 00:00 every day
    - cron: '0 0 * * *'

jobs:
  lock_closed:
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/lock-closed@91c9200c31977ecb179172cb67d288dc0ba390f3
        with:
          lock-bot-key: ${{ secrets.LOCK_BOT_PRIVATE_KEY }}
